export const GET_POST_OPTION_LIST = 'GET_POST_OPTION_LIST';

export const GET_UPCOMING_OPTION_LIST = 'GET_UPCOMING_OPTION_LIST';

export const GET_NOTICE_OPTION_LIST = 'GET_NOTICE_OPTION_LIST';

export const GET_CUST_BASE_PERMISSION = 'GET_CUST_BASE_PERMISSION';

export const GET_MATKL_AND_SHOP_DATA = 'GET_MATKL_AND_SHOP_DATA';

export const GET_ACCOUNT_DETAILS = 'GET_ACCOUNT_DETAILS';
