// 工程专区
export const GET_ENGINEER_LIST = 'GET_ENGINEER_LIST'
// 特惠专区
export const GET_PREFERENTIAL_LIST = 'GET_PREFERENTIAL_LIST'
// 套购专区
export const GET_BUYOUT_LIST = 'GET_BUYOUT_LIST'
// 品类查询和展示
export const GET_CLASSIFICATION_LIST = "GET_CLASSIFICATION_LIST"
// 筛选条件获取
export const GET_GOODS_FILTERS = "GET_GOODS_FILTERS"
// 特惠单筛选条件
export const GET_SPECIAL_FILTERS = "GET_SPECIAL_FILTERS"

// 获取价格
export const GET_CLASSIFICATION_PRICE = 'GET_CLASSIFICATION_PRICE'

// 获取库存
export const GET_CLASSIFICATION_STOCK = 'GET_CLASSIFICATION_STOCK'

// 图片404后，替换为默认图片
export const RESET_PRODUCT_IMG = 'RESET_PRODUCT_IMG'

// 更新是否收藏
export const TOGGLE_CLASSIFICATION_COLLECTION = 'TOGGLE_CLASSIFICATION_COLLECTION'

// 重置分类列表
export const RESET_CLASSIFICATION_LIST = 'RESET_CLASSIFICATION_LIST'
export const RESET_ENGINEER_LIST = 'RESET_ENGINEER_LIST'
export const RESET_PREFERENTIAL_LIST = 'RESET_PREFERENTIAL_LIST'
export const RESET_BUYOUT_LIST = 'RESET_BUYOUT_LIST'

// 三期物料组和供应商
export const GET_THREE_PHASE_MATERIAL_GROUP_AND_SUPPLIERS = 'GET_THREE_PHASE_MATERIAL_GROUP_AND_SUPPLIERS'
// 获取dms商品价格
export const GET_DMS_GOODS_PRICE = 'GET_DMS_GOODS_PRICE'
// 获取dms商品库存
export const GET_DMS_GOODS_INVENTORY = 'GET_DMS_GOODS_INVENTORY'

// 在Dms是否有权限判断
export const GET_AUTHORITY = 'GET_AUTHORITY'
// 获取橱窗未登录商品图
export const GET_PRODUCT = 'GET_PRODUCT'
