// 根据类目和产品组获取收藏列表
export const GET_COLLECTION_BY_GROUP_CATEGORY = 'GET_COLLECTION_BY_GROUP_CATEGORY';

// 购物车收藏列表
export const GET_COLLECTION_FROM_CART = 'GET_COLLECTION_FROM_CART';

// 将收藏设成空
export const RESET_COLLECTION_EMPTY = 'RESET_COLLECTION_EMPTY';

export const RESET_COLLECTION_IMG = 'RESET_COLLECTION_IMG';

// 获取价格
export const GET_COLLECTION_PRICE = 'GET_COLLECTION_PRICE';

// 获取库存
export const GET_COLLECTION_STOCK = 'GET_COLLECTION_STOCK';

// 获取渠道价格
export const GET_COLLECTION_DMS_PRICE = 'GET_COLLECTION_DMS_PRICE';
// res loadingprice
export const RESET_COLLECTION_LOAD = 'RESET_COLLECTION_LOAD';

