export const GET_CONSULT_TODO_ALL_ITEMS = 'GET_CONSULT_TODO_ALL_ITEMS';
export const GET_CONSULT_TODO_COUNTS = 'GET_CONSULT_TODO_COUNTS';
export const GET_CONSULT_TODO_ITEMS = 'GET_CONSULT_TODO_ITEMS';
export const GET_SHOP_FIX_TODO_ITEMS = 'GET_SHOP_FIX_TODO_ITEMS';
export const GET_SHOP_FIX_TODO_COUNTS = 'GET_SHOP_FIX_TODO_COUNTS';

export const GET_RECEIPT_COUNTS = 'GET_RECEIPT_COUNTS';
export const GET_RECEIPT_ITEMS = 'GET_RECEIPT_ITEMS';
export const GET_REPORT_COUNTS = 'GET_REPORT_COUNTS';
export const GET_REPORT_ITEMS = 'GET_REPORT_ITEMS';
export const GET_ASSESSMENT_NOTICE_COUNTS = 'GET_ASSESSMENT_NOTICE_COUNTS';
export const GET_ASSESSMENT_NOTICE_ITEMS = 'GET_ASSESSMENT_NOTICE_ITEMS';
export const GET_NEW_STORE_COUNTS = 'GET_NEW_STORE_COUNTS';
export const GET_NEW_STORE_ITEMS = 'GET_NEW_STORE_ITEMS';
