
export const GET_ACTIVITY_DESIGN_DATA = 'GET_ACTIVITY_DESIGN_DATA';

export const GET_ACTIVITY_BY_ID = 'GET_ACTIVITY_BY_ID';

export const GET_DESIGN_DATA_BY_ID = 'GET_DESIGN_DATA_BY_ID';

export const GET_TAB_ACTIVITY_BY_ID = 'GET_TAB_ACTIVITY_BY_ID';

export const GET_DESIGN_ALL = 'GET_DESIGN_ALL';
