
// 资金对账单列表接口
export const FINANCE_POST_RS_FT_SHEET_LIST = 'FINANCE_POST_RS_FT_SHEET_LIST';
// 重置资金对账单
export const RS_FT_SHEET_LIST='RS_FT_SHEET_LIST'


// 资金对账账单详情接口
export const FINANCE_POST_RS_FT_SHEET_DETAIL = 'FINANCE_POST_RS_FT_SHEET_DETAIL';

//发票三栏账列表查询接口
export const FINANCE_POST_RS_FT_SHEET_THREE = 'FINANCE_POST_RS_FT_SHEET_THREE';

//本期开票明细查询接口
export const FINANCE_POST_RS_FT_INVOICE_LIST = 'FINANCE_POST_RS_FT_INVOICE_LIST';

//海信方已发货未开票查询接口
export const FINANCE_POST_RS_FT_NO_INVOICE_LIST = 'FINANCE_POST_RS_FT_NO_INVOICE_LIST';

//本期回款明细查询接口
export const FINANCE_POST_RS_FT_INCOME_LIST = 'FINANCE_POST_RS_FT_INCOME_LIST';

//已退货未退税明细查询接口
export const FINANCE_POST_RS_FT_NO_REFUND_LIST = 'FINANCE_POST_RS_FT_NO_REFUND_LIST';

//重置发票页数据
export const RESET_RS_FT_LIST = 'RESET_RS_FT_LIST';

// 资金签章客户接口
export const RS_OC_FT_SHEET_BY_ROWID='RS_OC_FT_SHEET_BY_ROWID';

// 资金对账单app签章
export const RS_FT_CREATE_AND_SIGN = 'RS_FT_CREATE_AND_SIGN';
