export const GET_FFUND_CLAIM_COUNTS = 'GET_FFUND_CLAIM_COUNTS';
export const GET_FFUND_CLAIM_DETAIL = 'GET_FFUND_CLAIM_DETAIL';
export const POST_FUND_CLAIM_HANDLE = 'GET_FFUND_CLAIM_DETAIL';
export const GET_FUND_CLAIM_AGENCY = 'GET_FUND_CLAIM_AGENCY';
export const GET_FUND_CLAIM_BUSSINESS = 'GET_FUND_CLAIM_BUSSINESS';
export const GET_CAPITAL_FLOW_QUERY_CONDITIONS = 'GET_CAPITAL_FLOW_QUERY_CONDITIONS';
export const GET_CREDIT_RANGE = 'GET_CREDIT_RANGE';
export const GET_CAPITAL_FLOW_LIST = 'GET_CAPITAL_FLOW_LIST';
