export const GET_GOODS_PROMOTION = 'GET_GOODS_PROMOTION';
export const GET_GOODS_INFO = 'GET_GOODS_INFO';
export const GET_GOODS_PRICE = 'GET_GOODS_PRICE';
export const RESET_GOODS_INFO = 'RESET_GOODS_INFO';
// 获取dms价格和库存
export const GET_GOODS_DMS_PRICE = 'GET_GOODS_DMS_PRICE'
export const GET_GOODS_DMS_STOCK = 'GET_GOODS_DMS_STOCK'
export const GET_GOODS_STOCK = 'GET_GOODS_STOCK';

export const GET_GOODS_STOCK_KC = 'GET_GOODS_STOCK_KC'//库存(共享仓)
//定制产品
export const GET_GOODS_MODEL = 'GET_GOODS_MODEL';
//定制产品
export const GET_MODEL_GOODS_INFO = 'GET_MODEL_GOODS_INFO';



