export const GET_USER_HOME = 'GET_USER_HOME';
export const GET_USER_UNREAD_NUMBERS = 'GET_USER_UNREAD_NUMBERS';
// 首页提货报表接口
export const GEt_HOME_PAGE_PURCHASE_REPORT = 'GEt_HOME_PAGE_PURCHASE_REPORT'
// 首页销售报表接口
export const GEt_HOME_PAGE_SALES_REPORT = 'GEt_HOME_PAGE_SALES_REPORT'
// 首页库存报表接口
export const GEt_HOME_PAGE_INVENTORY_REPORT = 'GEt_HOME_PAGE_INVENTORY_REPORT'
// 当月每天库存变化报表接口
export const GEt_INV_CHANGE_EVERYDAY_REPORT = 'GEt_INV_CHANGE_EVERYDAY_REPORT'

export const GET_USER_UNREAD_DMS_NUMBERS = 'GET_USER_UNREAD_DMS_NUMBERS';
// 首页新增公告列表
export const GET_NEW_USER_LIST_INFO = 'GET_NEW_USER_LIST_INFO'
// 首页渠道报表
export const GET_NEW_HOME_CHANNEL_REPORTS = 'GET_NEW_HOME_CHANNEL_REPORTS'

export const GET_USER_UNREAD_CIS_AUDIT_ORDER = 'GET_USER_UNREAD_CIS_AUDIT_ORDER'

export const RESET_NEW_USER_LIST_INFO = 'RESET_NEW_USER_LIST_INFO'
// 首页运营报表接口
export const GET_OPERATE_PLAN_REACH = 'GET_OPERATE_PLAN_REACH'
// 首页动销录报表接口
export const GET_RURNOVER_RATE = 'GET_RURNOVER_RATE'
// 首页市场覆盖率
export const GET_MARKET_COVERAGE = 'GET_MARKET_COVERAGE'
// 销售结构
export const GET_PRODUCT_SALES_STRUCTURE = 'GET_PRODUCT_SALES_STRUCTURE'
// 毛利率
export const GET_GROSS_PROFIT_RATE = 'GET_GROSS_PROFIT_RATE'
// o2o
export const GET_O_2_O_SHOP_LIST = 'GET_O_2_O_SHOP_LIST'
// o2o收入报表
export const GET_SETTLE_STATISTIC = 'GET_SETTLE_STATISTIC'
// 写日志
export const WRITE_LOG = 'WRITE_LOG'
// 未读公告数量、未处理待办数量、未读消息数量接口
export const GET_UN_TREAT_NUM = 'GET_UN_TREAT_NUM'
// 首页导航图标查询-list
export const GET_NAVIGATION_MENU_RECORD = 'GET_NAVIGATION_MENU_RECORD'
