export const SET_INTENTION_APPLY = ' SET_INTENTION_APPLY';
export const SET_MATERIEL_APPLY = ' SET_MATERIEL_APPLY';
export const SET_INTENTION_GETCITY = ' SET_INTENTION_GETCITY';
export const SET_INTENTION_GETAREA = ' SET_INTENTION_GETAREA';
export const SET_INTENTION_GETTOWN = ' SET_INTENTION_GETTOWN';
export const SET_INTENTION_SEARCH = ' SET_INTENTION_SEARCH';
export const SET_INTENTION_ISRESPONSE = ' SET_INTENTION_ISRESPONSE';
export const SET_INTENTION_SENDSECURTYCODE = ' SET_INTENTION_SENDSECURTYCODE';

