// 库存列表
export const GET_INVENTORY_QUERIES_LIST = 'GET_INVENTORY_QUERIES_LIST'
// 重置库存列表
export const RESET_INVENTORY_QUERIES_LIST = 'RESET_INVENTORY_QUERIES_LIST'

// 分销商库存列表
export const GET_DISTRIBUTOR_INVENTORY_INQUIRY = 'GET_DISTRIBUTOR_INVENTORY_INQUIRY'
// 重置分销商库存列表
export const RESET_DISTRIBUTOR_INVENTORY_INQUIRY = 'RESET_DISTRIBUTOR_INVENTORY_INQUIRY'
// 获取补差类型
export const DMS_INV_STATUS_TYPE = 'DMS_INV_STATUS_TYPE'
// 库存调整入库查询列表
export const GET_INVENTORY_QUERIES_LIST_IN = 'GET_INVENTORY_QUERIES_LIST_IN'
// 重置库存调整入库查询列表
export const RESET_INVENTORY_QUERIES_LIST_IN = 'RESET_INVENTORY_QUERIES_LIST_IN'
//获取分销商商家列表
export const GET_DISTRIBUTOR_TYPE = 'GET_DISTRIBUTOR_TYPE'

//获取未结预留列表
export const GET_OPEN_RESERVATION = 'GET_OPEN_RESERVATION'
//重置未结预留列表
export const RESET_OPEN_RESERVATION = 'RESET_OPEN_RESERVATION'
// 查询样机库存总数
export const GET_FINDTAOJI_INVENTORY_TOTAL = 'GET_FINDTAOJI_INVENTORY_TOTAL'
// 查询单机库存
export const GET_SING_INVENTORY_QUERIES_LIST = 'GET_SING_INVENTORY_QUERIES_LIST'
