
// 采购报表
export const GET_REPORT_CUST_SALES='GET_REPORT_CUST_SALES';

// 采购报表供应商
export const GET_REPORT_SUPPLY_LIST = 'GET_REPORT_SUPPLY_LIST'

// 采购报表物料组
export const GET_REPORT_MATERIAL_LIST = 'GET_REPORT_MATERIAL_LIST'

// 五期渠道采购
export const GET_CHANNEL_REPORT_LIST = 'GET_CHANNEL_REPORT_LIST'
export const GET_CHANNEL_WLZ_LIST = 'GET_CHANNEL_WLZ_LIST'
// 360体验报表
export const GET_SAN_LIU_LING_EXPERIENCE_LIST = 'GET_SAN_LIU_LING_EXPERIENCE_LIST'
// 报表-详情
export const REPORT_DETAIL = 'REPORT_DETAIL'
// 首页-跑动率
export const GET_RUN_RATE = 'GET_RUN_RATE'
// 首页-回款提货额
export const GET_COLLECTION_DELIVERY = 'GET_COLLECTION_DELIVERY'
