// 获取退货单详情
export const GET_NEW_RETURN_ORDER_INFO = 'GET_NEW_RETURN_ORDER_INFO';
// 重置退货单详情
export const RESET_NEW_RETURN_ORDER_INFO = 'RESET_RETURN_ORDER_INFO';

// 新确认入库
export const GET_CONFIRMATION_INBOUND = 'GET_CONFIRMATION_INBOUND';


// 渠道退货详情
export const GET_NEW_RETURN_ORDER_CHANNEL_INFO = 'GET_NEW_RETURN_ORDER_CHANNEL_INFO';
// 重置退货详情
export const RESET_NEW_RETURN_ORDER_CHANNEL_INFO = 'RESET_NEW_RETURN_ORDER_CHANNEL_INFO';
// 退货确认
export const GET_CONFIRMATION_CHANNEL_INBOUND = 'GET_CONFIRMATION_CHANNEL_INBOUND';
