
// 获取客户选择列表
export const GET_RETURN_ORDER_INFO = 'GET_RETURN_ORDER_INFO';
// 重置客户选择列表
export const RESET_RETURN_ORDER_INFO = 'RESET_RETURN_ORDER_INFO';


// 渠道退货单客户选择列表
export const GET_RETURN_CHANNEL_ORDER_INFO = 'GET_RETURN_CHANNEL_ORDER_INFO';
// 重置渠道退货单列表
export const RESET_RETURN_CHANNEL_ORDER_INFO = 'RESET_RETURN_CHANNEL_ORDER_INFO';
// 分销商采购单退货详情-退货发起
export const GET_PURCHASE_ORDER_RETURN_DETAIL = 'GET_PURCHASE_ORDER_RETURN_DETAIL';
// 分销商发起退货提交
export const CREATE_RETURN_ORDER_BY_PURCHASE_ORDER = 'CREATE_RETURN_ORDER_BY_PURCHASE_ORDER';
// 分销商退货详情-退货出库
export const GET_DISTRIBUTOR_RETURN_ORDER_DETAIL = 'GET_DISTRIBUTOR_RETURN_ORDER_DETAIL';
// 分销商退货出库提交
export const CREATE_DISTRIBUTOR_RETURN_ORDER_OUT_BOUND = 'CREATE_DISTRIBUTOR_RETURN_ORDER_OUT_BOUND';
// 代理商销售单退货详情-退货发起
export const GET_RETURN_SHOW_SALES_ORDER = 'GET_RETURN_SHOW_SALES_ORDER';
// 代理商发起退货提交
export const CREATE_CHANNEL_CREATION_RETURN = 'CREATE_CHANNEL_CREATION_RETURN';
// 代理商销售单退货详情-退货入库
export const GET_AGENT_RETURN_ORDER_DETAIL = 'GET_AGENT_RETURN_ORDER_DETAIL';
// 代理商退货入库提交
export const CREATE_AGENT_RETURN_ORDER_INBOUND = 'CREATE_AGENT_RETURN_ORDER_INBOUND';
// 代理商退货入库取消退货
export const CANCEL_RETURN = 'CANCEL_RETURN';

