// 订单列表
export const GET_SALES_ORDER_LIST = 'GET_SALES_ORDER_LIST';

//基础信息
export const GET_SALES_ORDER_FILTER = 'GET_SALES_ORDER_FILTER';

//取消订单
export const CANCLE_SALES_ORDER = 'CANCLE_SALES_ORDER';

//删除订单
export const DELETE_SALES_ORDER = 'DELETE_SALES_ORDER';

// 渠道采购订单列表
export const GET_PURCHASE_ORDER_LIST = 'GET_PURCHASE_ORDER_LIST';

//重置渠道采购订单列表
export const RESET_PURCHASE_ORDER_LIST = 'RESET_PURCHASE_ORDER_LIST';

// 销售订单驳回
export const SALES_ORDER_REJECTED = 'SALES_ORDER_REJECTED';

// 销售订单审核同意
export const SALES_ORDER_APPROVAL = 'SALES_ORDER_APPROVAL';

// 重置渠道订单查询列表
export const RESET_SALES_ORDER_INQUIRY_LIST = 'RESET_SALES_ORDER_INQUIRY_LIST';

// 代理商取消订单
export const AGENT_CANCELE_ORDER = 'AGENT_CANCELE_ORDER'

// 取消审核
export const CANSEL_ORDER_EXAMIN = 'CANSEL_ORDER_EXAMIN';