export const GET_SEARCH_GOODS = 'GET_SEARCH_GOODS';

export const GET_SEARCH_PRICE = 'GET_SEARCH_PRICE';

export const GET_SEARCH_STOCK = 'GET_SEARCH_STOCK'

export const RESET_SEARCH_IMG = 'RESET_SEARCH_IMG'

export const TOGGLE_SEARCH_COLLECTION = 'TOGGLE_SEARCH_COLLECTION'
// 重置
export const RESET_SEARCH_LIST = 'RESET_SEARCH_LIST'
// dms 物料组
export const GET_FILTER_ITEM_GROUP = 'GET_FILTER_ITEM_GROUP'
// 组织
export const GET_FX_DICT_CIS_CODE = 'GET_FX_DICT_CIS_CODE'
// dms 价格
export const GET_FILTER_DMS_GOODS_PRICE = 'GET_FILTER_DMS_GOODS_PRICE'
// dms 库存
export const GET_DMS_GOODS_INVENTORY = 'GET_DMS_GOODS_INVENTORY'
// 分销商
export const FX_DICT_CIS_CODE = 'FX_DICT_CIS_CODE'
// 专卖店
export const GET_EXCLUSIVE_SHOP_BY_CIS_CODE = 'GET_EXCLUSIVE_SHOP_BY_CIS_CODE'
