export const GET_EXAMINFO = 'GET_EXAMINFO';
export const SUBMIT_EXAMINFO = 'SUBMIT_EXAMINFO';
//商家查询待答问卷列表
export const GET_TOBE_ANSWERED_QUESTION = 'GET_TOBE_ANSWERED_QUESTION';
//查询当前商家已答问卷列表
export const GET_ANSWERED_QUESTION_LIST = 'GET_ANSWERED_QUESTION_LIST';
// 重置问卷列表
export const RESET_ANSWERED_QUESTION = 'RESET_ANSWERED_QUESTION';
