export const GET_SHOP_TODO_COUNTS = 'GET_SHOP_TODO_COUNTS';

export const GET_SHOP_TODO_ITEMS = 'GET_SHOP_TODO_ITEMS';

export const GET_REPORT_ITEMS = 'GET_REPORT_ITEMS';

export const GET_RECEIPT_ITEMS = 'GET_RECEIPT_ITEMS';

export const GET_REPORT_COUNTS = 'GET_REPORT_COUNTS';

export const GET_RECEIPT_COUNTS = 'GET_RECEIPT_COUNTS';
