export const GET_USER_INFO = 'GET_USER_INFO';
export const USER_LOGIN_ACTION = 'USER_LOGIN_ACTION';
export const USER_LOGOUT_ACTION = 'USER_LOGOUT_ACTION';
export const USER_BIND_ACTION = 'USER_BIND_ACTION';
export const USER_PERMISSIONS = 'USER_PERMISSIONS';
export const USER_ALERT = 'USER_ALERT';
export const ADD_MENU_RECORD = 'ADD_MENU_RECORD';
export const GET_MENU_RECORD = 'GET_MENU_RECORD';
export const GET_COMM_PAGE = 'GET_COMM_PAGE';
export const SEND_MSG = 'SEND_MSG';
export const GET_CANCELLATION_REASON = 'GET_CANCELLATION_REASON';
export const APPLY_CANCEL_ACCOUNT = 'APPLY_CANCEL_ACCOUNT';
export const CANCEL_ACCOUNT = 'CANCEL_ACCOUNT';

